//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6MySQL.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public string AMPHUR_CODE { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string DISTRICT_NAME_ENG { get; set; }
        public string ZIPCODE { get; set; }
        public string USER_UPDATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
    
        public virtual amphure amphure { get; set; }
    }
}
