//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6MySQL.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class province
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public province()
        {
            this.amphures = new HashSet<amphure>();
        }
    
        public string PROVINCE_CODE { get; set; }
        public string NCB_CATALOG_ID { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string PROVINCE_NAME_ENG { get; set; }
        public string DIMENSION4 { get; set; }
        public string DIMENSION5 { get; set; }
        public string REGION_ID { get; set; }
        public string THAI_SHORT_NAME { get; set; }
        public string ENG_SHORT_NAME { get; set; }
        public string USER_UPDATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amphure> amphures { get; set; }
    }
}
